# Pinea versión exacta. Verifica la última en github.com/open-telemetry/opentelemetry-collector-releases
FROM otel/opentelemetry-collector-contrib:0.161.0
COPY config.yaml /etc/otelcol-contrib/config.yaml
CMD ["--config", "/etc/otelcol-contrib/config.yaml"]
